FROM apache/spark:latest

USER root

COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

ENV HF_HOME=/opt/hf_cache
ENV TRANSFORMERS_CACHE=/opt/hf_cache
RUN mkdir -p /opt/hf_cache && chmod -R 777 /opt/hf_cache

RUN mkdir -p /home/spark && chown -R 185:185 /home/spark
ENV HOME=/home/spark

WORKDIR /opt/spark-apps
COPY ./src /opt/spark-apps
COPY ./config /opt/spark-config

USER 185
CMD ["bash"]
