FROM bitnami/spark:3.5

USER root
RUN apt-get update && apt-get install -y python3-pip
COPY ../requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

WORKDIR /src
COPY src /src
COPY config /config

ENTRYPOINT ["spark-submit", "--master", "local[*]", "/src/main.py"]